version: '3.8'

services:
  <service-name>:
    build: .
    container_name: <product-service>
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - zalando-backend

networks:
  zalando-backend:
    external: true